# Generated by Django 4.2.1 on 2023-06-03 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="staffprofile",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="staffprofile",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="created",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="created",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
