# Generated by Django 4.2.1 on 2023-05-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BZS", "BUSINESS SUITE"),
                            ("TWS", "TWIN SUITE"),
                            ("EXS", "EXECUTIVE SUITE"),
                            ("SGB", "SINGLE BED"),
                        ],
                        max_length=3,
                    ),
                ),
                ("beds", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                (
                    "status",
                    models.BooleanField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.room"
                    ),
                ),
            ],
        ),
    ]
