# Generated by Django 4.2.1 on 2023-06-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_alter_category_updated_alter_reservation_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="hotel.category"
            ),
        ),
    ]
