# Generated by Django 4.2.1 on 2023-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="cancellation_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
