# Generated by Django 4.2.1 on 2023-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_alter_room_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("FULFILLED", "Fulfilled"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
