# Generated by Django 4.2.1 on 2023-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0005_remove_category_image_url_category_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_file",
            field=models.ImageField(null=True, upload_to="images/category/"),
        ),
    ]
